management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    tags:
      application: app
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: 'true'
logging:
  pattern:
    level: "trace_id=%mdc{trace_id} span_id=%mdc{span_id} trace_flags=%mdc{trace_flags} %p"
  level:
    com.example.app: DEBUG

spring:
  application.name: spring-boot-observability-sample
  datasource:
    url: jdbc:postgresql://postgres:5432/peanuts
    username: yu71
    password: 53cret
  jpa:
    hibernate:
      ddl-auto: update
      sql-log:
        format: true
    show-sql: true
  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379
